version: '3.8'

services:
  quiz-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json
      - ./quiz_bot/quizzes:/app/quizzes
    restart: unless-stopped
    container_name: quiz-bot